import type { LabelTemplate, TemplateId } from "@/types";

export const TEMPLATES: Record<TemplateId, LabelTemplate> = {
  auspost_qr: {
    id: "auspost_qr",
    name: "Australia Post no-label QR",
    shortName: "AusPost QR",
    carrier: "Australia Post",
    type: "No-label QR drop-off",
    codeType: "qr",
    codeLabel: "Return Code",
    accent: "#2257c8",
    aspectRatio: 1,
    dropoffLink: "https://auspost.com.au/locate/?services=9",
    showItemTable: true,
    instructions: [
      "Australia Post (post office) will be able to accept the return successfully after 30 mins. Please ensure to drop the parcel only at Australia Post (post office). Click the link below to find no-label drop off locations:",
      "Show the code and Australia Post will print the label for you.",
    ],
    validityCopy:
      "The return code is valid for 14 days from creation date. If your code expires and your item is still eligible for returns, contact seller to request a new return.",
    dropoffNote: "Drop off at Australia Post only. Do not place no-label returns in street posting boxes.",
  },
  auspost_label: {
    id: "auspost_label",
    name: "Australia Post printable label",
    shortName: "AusPost label",
    carrier: "Australia Post",
    type: "Printable label",
    codeType: "label",
    codeLabel: "Return Mailing Label",
    accent: "#21704c",
    aspectRatio: 1.5,
    showItemTable: false,
    secondaryCodeLabel: "Return Authorisation Label",
    secondaryCodeHelp: "Cut this and place inside the return package",
    secondaryCodeType: "barcode",
    secondaryAspectRatio: 3.45,
    secondaryRequired: true,
    instructions: [
      "Ensure that there are no tracking labels attached to your package. If you are shipping a non-hazardous item, completely remove or cover any hazardous material markings.",
      "Affix the postage label squarely onto the address side of the parcel, covering up any previous delivery address and barcode without overlapping any adjacent side.",
      "Take the package to an Australia Post location or drop it in a street posting box. To find your closest Australia Post location, visit https://auspost.com.au/locate",
    ],
    validityCopy: "Cut this label and affix to the outside of the return package",
    dropoffNote: "Accepted at Australia Post return locations. Keep proof of lodgement.",
  },
  parcelpoint_barcode: {
    id: "parcelpoint_barcode",
    name: "ParcelPoint no-label barcode (Hubbed)",
    shortName: "ParcelPoint code (Hubbed)",
    carrier: "ParcelPoint",
    type: "No-label barcode drop-off",
    codeType: "barcode",
    codeLabel: "Return Code",
    accent: "#7d4ac7",
    aspectRatio: 3.45,
    dropoffLink: "https://parcelpoint.com.au/find-a-store",
    dropoffLinkInstructionIndex: 1,
    showItemTable: true,
    instructions: [
      "The Parcelpoint store will be able to accept the return successfully after 30 mins. Please ensure to drop the parcel only in the Parcelpoint store.",
      "Show the code and ParcelPoint will print the label for you. The package should be taken only to ParcelPoint DropOff location:",
      "Please do NOT print the Commercial Invoice. It is provided for your records only, and does not need to be included in your return package.",
    ],
    validityCopy:
      "The return code is valid for 14 days from creation date. If your code expires and your item is still eligible for returns, contact seller to request a new return.",
    dropoffNote: "Drop off at ParcelPoint partner locations only.",
  },
  parcelpoint_label: {
    id: "parcelpoint_label",
    name: "ParcelPoint printable label (Hubbed)",
    shortName: "ParcelPoint label (Hubbed)",
    carrier: "ParcelPoint",
    type: "Printable label",
    codeType: "label",
    codeLabel: "Return Mailing Label",
    accent: "#9a5b0f",
    aspectRatio: 1.5,
    showItemTable: false,
    secondaryCodeLabel: "Return Authorisation Label",
    secondaryCodeHelp: "Cut this and place inside the return package",
    secondaryCodeType: "barcode",
    secondaryAspectRatio: 3.45,
    secondaryRequired: true,
    instructions: [
      "Print this label and attach it securely to the outside of the package.",
      "Drop off the parcel at a ParcelPoint partner location.",
      "Keep the lodgement receipt until the return is completed.",
    ],
    validityCopy: "Cut this label and affix to the outside of the return package",
    dropoffNote: "Accepted at ParcelPoint partner locations only.",
  },
  parcelpoint_pickup: {
    id: "parcelpoint_pickup",
    name: "ParcelPoint pick-up label (Hubbed)",
    shortName: "ParcelPoint pick-up (Hubbed)",
    carrier: "ParcelPoint",
    type: "Pick-up label",
    codeType: "label",
    codeLabel: "Return Mailing Label",
    accent: "#dc2626",
    aspectRatio: 0.95,
    showItemTable: true,
    secondaryCodeLabel: "Return Authorisation Label",
    secondaryCodeHelp: "Cut this and place inside the return package",
    secondaryCodeType: "barcode",
    secondaryAspectRatio: 3.45,
    secondaryRequired: true,
    instructions: [
      "Parcel Point will collect your parcel within next two business days (Mon-Fri: 8AM – 5PM, excluding holidays), as long as the collection is booked before 11:30PM local time.",
      "Print your return label and securely pack your item(s) to be returned before collection. Parcel Point will be unable to collect the item(s) if you do not have a printed return label secured to the outside of the package.",
      "Return the item in the original condition and packaging, unless the item was damaged upon receipt. Make sure an adult is present at the time of pickup.",
      "If you cannot be present for the first pickup attempt, please call Parcel Point customer service at 1300 025 639 within 48 hrs of failed pickup attempt to schedule the second time pickup. Parcel Point customer service operation hours are Mon-Fri: 8:30AM to 7:30PM; Sat: 9AM - 3PM; Sun: 11AM - 3PM. If the second pickup attempt fails, please contact the seller to create a new return request.",
    ],
    validityCopy: "Cut this label and affix to the outside of the return package",
    dropoffNote: "Scheduled collection by ParcelPoint. Keep proof of booking.",
  },
};

export const TEMPLATE_IDS = Object.keys(TEMPLATES) as TemplateId[];
